language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-react-rails-browserify' ]; then cd .. && eval "mv $currentfolder generator-react-rails-browserify" && cd generator-react-rails-browserify; fi
